/**
 * ClientHello construction (RFC 8446 §4.2).
 *
 * Serializes the client's opening handshake message: legacy version + random +
 * session id + cipher suites + the extensions that actually drive TLS 1.3
 * negotiation (SNI, supported_versions, key_share, signature_algorithms, ALPN).
 * This is the only place that knows the ClientHello wire layout; the rest of the
 * handshake module only consumes the bytes it produces.
 */

import { crypto } from "@browsercore/crypto";
import type {
    CipherSuite,
    ClientHelloConfig,
    ClientHelloPskParams,
    KeyPair,
    NamedGroup,
    ProtocolVersion,
    SignatureScheme,
} from "../types.js";
import { TlsHandshakeError } from "../errors.js";
import { assertNever } from "../utils.js";
import { ExtensionType, namedGroupToWire, signatureSchemeToWire } from "../extensions/extensions.js";
import { computeBinder, deriveBinderKey, deriveEarlySecretFromPsk, hashFor } from "../crypto/keySchedule.js";
import { HandshakeType } from "./handshake-types.js";

/** TLS 1.2 wire version used as legacy_version in TLS 1.3 records/handshakes. */
const TLS_1_2_WIRE_VERSION = 0x0303;

/**
 * GREASE (RFC 8701) reserved cipher-suite sentinel. Real browsers randomize the
 * exact 0x?a?a value per-connection; we use the canonical first GREASE code.
 */
const GREASE_CIPHER_WIRE = 0x0a0a;

/** GREASE extension-type sentinel (0x0a0a). */
const GREASE_EXTENSION_WIRE = 0x0a0a;

/**
 * Length (bytes) of the key-exchange blob we emit for a GREASE key-share entry.
 * Matches X25519 so the GREASE entry is indistinguishable in size from a real one.
 */
const GREASE_KEY_LENGTH = 32;

/**
 * Cipher suite IANA wire values.
 *
 * Covers every suite the shipped browser profiles offer: the four TLS 1.3 AEAD
 * suites (the only ones a TLS 1.3 handshake can *negotiate*) plus the TLS 1.2
 * suites and the GREASE placeholder that real Chrome places in the *offered*
 * ClientHello list for middlebox compatibility. Values come from the IANA TLS
 * Cipher Suite Registry and match `@browsercore/profiles`' canonical table.
 */
export function cipherSuiteToWire(suite: CipherSuite): number {
    switch (suite) {
        // GREASE sentinel (RFC 8701). Real value is randomized per-connection.
        case "TLS_GREASE_RESERVED_0":
            return GREASE_CIPHER_WIRE;
        // TLS 1.3 AEAD suites (the only ones this client can negotiate).
        case "TLS_AES_128_GCM_SHA256":
            return 0x1301;
        case "TLS_AES_256_GCM_SHA384":
            return 0x1302;
        case "TLS_CHACHA20_POLY1305_SHA256":
            return 0x1303;
        case "TLS_AES_128_CCM_SHA256":
            return 0x1304;
        // TLS 1.2 ECDHE/GCM suites.
        case "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256":
            return 0xc02b;
        case "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256":
            return 0xc02f;
        case "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384":
            return 0xc02c;
        case "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384":
            return 0xc030;
        case "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256":
            return 0xcca9;
        case "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256":
            return 0xcca8;
        // TLS 1.2 ECDHE/CBC suites.
        case "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA":
            return 0xc013;
        case "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA":
            return 0xc014;
        case "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA":
            return 0xc009;
        case "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA":
            return 0xc00a;
        // TLS 1.2 RSA suites.
        case "TLS_RSA_WITH_AES_128_GCM_SHA256":
            return 0x009c;
        case "TLS_RSA_WITH_AES_256_GCM_SHA384":
            return 0x009d;
        case "TLS_RSA_WITH_AES_128_CBC_SHA":
            return 0x002f;
        case "TLS_RSA_WITH_AES_256_CBC_SHA":
            return 0x0035;
        default:
            // Every CipherSuite member is covered above; this is unreachable but
            // keeps the switch exhaustive if the union is ever extended.
            return assertNever(suite);
    }
}

/**
 * Build a ClientHello handshake message from the given config.
 *
 * Serializes the full handshake message (header + body) with extensions for SNI,
 * supported_versions, key_share, signature_algorithms, and (optionally) ALPN.
 * The (EC)DHE public keys come from `keyPairs` (already generated by the caller
 * via @browsercore/crypto).
 *
 * When `config.psk` is provided (session resumption), the pre_shared_key
 * extension is emitted with the ticket identity + binder values, and the
 * early_data extension is emitted if `psk.offerEarlyData` is set. The
 * `psk.cipherSuite` selects the hash for the binder computation.
 *
 * The `random` value is generated exactly once and threaded through to both the
 * wire message and the PSK binder transcript, so the binder authenticates over
 * the same random the server sees (RFC 8446 §4.2.11.2).
 *
 * @param config   ClientHello configuration (includes optional `psk`).
 * @param keyPairs (EC)DHE key pairs for the key_share extension.
 * @param random   Optional 32-byte ClientHello random. When omitted, a fresh
 *                 random is generated. When supplied, that exact value is used
 *                 on the wire AND in the PSK binder transcript — so tests can
 *                 pin it and assert deterministic binders.
 */
export function buildClientHello(
    config: ClientHelloConfig,
    keyPairs: readonly KeyPair[],
    random?: Uint8Array,
): Uint8Array {
    const clientRandom = random ?? crypto.randomBytes(32);
    const sessionId = new Uint8Array(0);
    const compressionMethods = new Uint8Array([0x00]);

    const extensions = buildClientHelloExtensions(config, keyPairs, clientRandom, config.psk);

    // Body length: version(2) + random(32) + session_id_len(1) + session_id +
    //   cipher_suites_len(2) + cipher_suites + compression_len(1) + compression +
    //   extensions_len(2) + extensions.
    //
    // Map every offered cipher suite to its 2-byte IANA wire value. The profile
    // data encodes GREASE positions via the TLS_GREASE_RESERVED_0 placeholder,
    // which maps to 0x0a0a. As a safety net, when grease is enabled we ensure a
    // GREASE sentinel leads the list even if the profile omitted the placeholder.
    const cipherWires: number[] = config.cipherSuites.map((suite, i) => {
        if (suite === undefined) {
            throw new TlsHandshakeError("client_hello", {
                cause: new Error(`cipher suite at index ${i} is missing`),
            });
        }
        return cipherSuiteToWire(suite);
    });
    if (config.grease && (cipherWires.length === 0 || cipherWires[0] !== GREASE_CIPHER_WIRE)) {
        cipherWires.unshift(GREASE_CIPHER_WIRE);
    }
    const cipherSuitesBytes = new Uint8Array(cipherWires.length * 2);
    for (let i = 0; i < cipherWires.length; i++) {
        const wire = cipherWires[i];
        if (wire === undefined) {
            // cipherWires.length bounds this loop, so this is unreachable — but
            // noUncheckedIndexedAccess can't prove it, so read through a local.
            throw new TlsHandshakeError("client_hello", {
                cause: new Error(`cipher suite wire at index ${i} is missing`),
            });
        }
        cipherSuitesBytes[i * 2] = (wire >> 8) & 0xff;
        cipherSuitesBytes[i * 2 + 1] = wire & 0xff;
    }

    const bodyLen =
        2 + clientRandom.length + 1 + sessionId.length +
        2 + cipherSuitesBytes.length +
        1 + compressionMethods.length +
        2 + extensions.length;

    // Handshake header: msg_type(1) + length(24-bit) + body.
    const message = new Uint8Array(1 + 3 + bodyLen);
    let o = 0;
    message[o++] = HandshakeType.CLIENT_HELLO;
    message[o++] = (bodyLen >> 16) & 0xff;
    message[o++] = (bodyLen >> 8) & 0xff;
    message[o++] = bodyLen & 0xff;

    // legacy_version = 0x0303 (TLS 1.2 for middlebox compatibility).
    message[o++] = (TLS_1_2_WIRE_VERSION >> 8) & 0xff;
    message[o++] = TLS_1_2_WIRE_VERSION & 0xff;
    message.set(clientRandom, o);
    o += clientRandom.length;

    // Session ID (length-prefixed; empty for TLS 1.3).
    message[o++] = sessionId.length & 0xff;
    message.set(sessionId, o);
    o += sessionId.length;

    // Cipher suites (length-prefixed).
    message[o++] = (cipherSuitesBytes.length >> 8) & 0xff;
    message[o++] = cipherSuitesBytes.length & 0xff;
    message.set(cipherSuitesBytes, o);
    o += cipherSuitesBytes.length;

    // Compression methods (length-prefixed; single null).
    message[o++] = compressionMethods.length & 0xff;
    message.set(compressionMethods, o);
    o += compressionMethods.length;

    // Extensions (length-prefixed).
    message[o++] = (extensions.length >> 8) & 0xff;
    message[o++] = extensions.length & 0xff;
    message.set(extensions, o);

    return message;
}

/**
 * Serialize the extensions block for a ClientHello. Each extension is
 * type(2) || data_len(2) || data, all under a single length-prefix.
 *
 * Extensions are emitted in the exact order given by `config.extensionOrder`,
 * which is the primary TLS fingerprinting signal. Every type the profile lists
 * must have a matching encoder; an unknown type is a bug in the profile data
 * and fails fast rather than emitting a malformed/omitted extension.
 *
 * When GREASE is enabled, a GREASE extension (type 0x0a0a, empty body) is
 * prepended ahead of the profile's order, matching real-browser behavior.
 *
 * When `psk` is set, the pre_shared_key extension body is computed by first
 * emitting a truncated ClientHello (PSK identities only, no binders), then
 * computing the binder over that truncated message, then emitting the final
 * PSK extension with identities + binders. RFC 8446 §4.2.11.2. The same
 * `random` used on the wire is threaded into the binder transcript.
 */
function buildClientHelloExtensions(
    config: ClientHelloConfig,
    keyPairs: readonly KeyPair[],
    random: Uint8Array,
    psk?: ClientHelloPskParams,
): Uint8Array {
    // When resuming with 0-RTT intent, inject the early_data extension (42)
    // immediately after pre_shared_key (41) — matching real-browser layout. It
    // is emitted with an empty body; its presence alone signals 0-RTT intent
    // (RFC 8446 §4.2.10).
    let order: number[];
    if (psk?.offerEarlyData === true) {
        const withEarly: number[] = [];
        for (const t of config.extensionOrder) {
            withEarly.push(t);
            if (t === ExtensionType.PRE_SHARED_KEY) {
                withEarly.push(ExtensionType.EARLY_DATA);
            }
        }
        order = config.grease ? [GREASE_EXTENSION_WIRE, ...withEarly] : withEarly;
    } else {
        order = config.grease
            ? [GREASE_EXTENSION_WIRE, ...config.extensionOrder]
            : [...config.extensionOrder];
    }

    const parts: Uint8Array[] = [];
    for (const type of order) {
        // The pre_shared_key extension requires special two-phase emission when
        // resuming: compute the binder over a truncated ClientHello that uses
        // the SAME random as the wire message. Skip the standard encoder for
        // type 41 when psk is set.
        if (type === ExtensionType.PRE_SHARED_KEY && psk !== undefined) {
            parts.push(buildPskExtensionWithBinder(config, keyPairs, random, psk));
            continue;
        }
        const body = encodeExtensionBody(type, config, keyPairs);
        parts.push(wrapExtension(type, body));
    }

    let total = 0;
    for (const p of parts) {
        total += p.length;
    }
    const out = new Uint8Array(total);
    let o = 0;
    for (const p of parts) {
        out.set(p, o);
        o += p.length;
    }
    return out;
}

/**
 * Dispatch an extension type to its body encoder. Centralizes the type→encoder
 * mapping so the emission loop stays a thin iteration over the profile order.
 */
function encodeExtensionBody(type: number, config: ClientHelloConfig, keyPairs: readonly KeyPair[]): Uint8Array {
    switch (type) {
        case ExtensionType.SERVER_NAME:
            return encodeServerNameList(config.serverName);
        case ExtensionType.STATUS_REQUEST:
            return encodeStatusRequest();
        case ExtensionType.SUPPORTED_GROUPS:
            return encodeSupportedGroups(config.keyShareGroups);
        case ExtensionType.EC_POINT_FORMATS:
            return encodeEcPointFormats();
        case ExtensionType.SIGNATURE_ALGORITHMS:
            return encodeSignatureAlgorithms(config.signatureAlgorithms);
        case ExtensionType.APPLICATION_LAYER_PROTOCOL_NEGOTIATION:
            // ALPN is only meaningful when the client actually offers protocols.
            return config.alpnProtocols !== undefined && config.alpnProtocols.length > 0
                ? encodeAlpn(config.alpnProtocols)
                : new Uint8Array(0);
        case ExtensionType.APPLICATION_SETTINGS:
            return encodeApplicationSettings(config.alpnProtocols);
        case ExtensionType.SIGNED_CERTIFICATE_TIMESTAMP:
            return new Uint8Array(0);
        case ExtensionType.EXTENDED_MASTER_SECRET:
            return new Uint8Array(0);
        case ExtensionType.COMPRESS_CERTIFICATE:
            return encodeCompressCertificate();
        case ExtensionType.SESSION_TICKET:
            return new Uint8Array(0);
        case ExtensionType.PRE_SHARED_KEY:
            // Standard (non-resumed) path: emit an empty body. Resumed
            // handshakes go through buildPskExtensionWithBinder instead (which
            // does the two-phase binder computation over the shared random).
            // This fallback preserves the profile's extension order when no PSK
            // is configured but the type is present in the order.
            return new Uint8Array(0);
        case ExtensionType.EARLY_DATA:
            // RFC 8446 §4.2.10: the early_data extension in ClientHello carries
            // an empty body; its presence alone signals 0-RTT intent. Only
            // emitted when injected into the order by buildClientHelloExtensions
            // (offerEarlyData path).
            return new Uint8Array(0);
        case ExtensionType.SUPPORTED_VERSIONS:
            return encodeSupportedVersionsClient(config.supportedVersions);
        case ExtensionType.PSK_KEY_EXCHANGE_MODES:
            return encodePskKeyExchangeModes();
        case ExtensionType.KEY_SHARE:
            return encodeKeyShareClient(config, keyPairs);
        case ExtensionType.RENEGOTIATION_INFO:
            return encodeRenegotiationInfo();
        default:
            // A GREASE extension (0x?a?a) or any other type without a body
            // encoder is emitted with an empty body — exactly what real browsers
            // do for GREASE values.
            if (isGreaseValue(type)) {
                return new Uint8Array(0);
            }
            throw new TlsHandshakeError("client_hello", {
                cause: new Error(`no encoder for extension type 0x${type.toString(16)}`),
            });
    }
}

/**
 * A GREASE value follows the 0x?a?a pattern (byte 0x? a repeated), per RFC 8701.
 * Both bytes are identical and each byte's low nibble is 0xa.
 */
function isGreaseValue(type: number): boolean {
    const hi = (type >> 8) & 0xff;
    const lo = type & 0xff;
    return type > 0 && hi === lo && (lo & 0x0f) === 0x0a;
}

/** Encode the supported_groups extension body (RFC 8446 §4.2.7). */
function encodeSupportedGroups(groups: readonly NamedGroup[]): Uint8Array {
    const out = new Uint8Array(2 + groups.length * 2);
    out[0] = ((groups.length * 2) >> 8) & 0xff;
    out[1] = (groups.length * 2) & 0xff;
    for (let i = 0; i < groups.length; i++) {
        const group = groups[i];
        if (group === undefined) {
            throw new TlsHandshakeError("client_hello", {
                cause: new Error(`supported group at index ${i} is missing`),
            });
        }
        const wire = namedGroupToWire(group);
        out[2 + i * 2] = (wire >> 8) & 0xff;
        out[2 + i * 2 + 1] = wire & 0xff;
    }
    return out;
}

/**
 * Encode the ec_point_formats extension body (RFC 4492 §5.1). Chrome sends only
 * uncompressed (0x00).
 */
function encodeEcPointFormats(): Uint8Array {
    return new Uint8Array([0x01, 0x00]);
}

/**
 * Encode the application_settings (ALPN) extension body (RFC 8441). Carries the
 * same protocol list as ALPN. Defaults to "h2" when no ALPN protocols are set.
 */
function encodeApplicationSettings(alpnProtocols: readonly string[] | undefined): Uint8Array {
    const protocols = alpnProtocols !== undefined && alpnProtocols.length > 0 ? alpnProtocols : ["h2"];
    return encodeAlpn(protocols);
}

/**
 * Encode the compress_certificate extension body (RFC 8879 §3). Chrome 140
 * advertises zlib (0x0001), brotli (0x0002), and zstd (0x0003).
 */
function encodeCompressCertificate(): Uint8Array {
    const algorithms = [0x0001, 0x0002, 0x0003];
    const out = new Uint8Array(1 + algorithms.length * 2);
    out[0] = (algorithms.length * 2) & 0xff;
    for (let i = 0; i < algorithms.length; i++) {
        const algo = algorithms[i];
        if (algo === undefined) {
            // algorithms.length bounds this loop, so this is unreachable.
            throw new TlsHandshakeError("client_hello", {
                cause: new Error(`compress certificate algorithm at index ${i} is missing`),
            });
        }
        out[1 + i * 2] = (algo >> 8) & 0xff;
        out[1 + i * 2 + 1] = algo & 0xff;
    }
    return out;
}

/** Encode the psk_key_exchange_modes extension body (RFC 8446 §4.2.9). */
function encodePskKeyExchangeModes(): Uint8Array {
    // psk_dhe_ke (1) is the only mode TLS 1.3 resumption uses.
    return new Uint8Array([0x01, 0x01]);
}

/** Encode the status_request extension body (RFC 6066 §8) — OCSP only. */
function encodeStatusRequest(): Uint8Array {
    // status_type=1 (OCSP) + empty responder_id_list + empty request_extensions.
    return new Uint8Array([0x01, 0x00, 0x00, 0x00, 0x00]);
}

/** Encode the renegotiation_info extension body (RFC 5746 §3.2). */
function encodeRenegotiationInfo(): Uint8Array {
    // renegotiated_connection length = 0 (no renegotiation in progress).
    return new Uint8Array([0x00]);
}

/**
 * Wrap an extension body with its type + length prefix.
 *
 * Accepts a raw `number` (not just the `ExtensionType` union) so GREASE
 * extension types (0x?a?a) and any future type can be emitted without a cast.
 */
function wrapExtension(type: number, data: Uint8Array): Uint8Array {
    const out = new Uint8Array(2 + 2 + data.length);
    out[0] = (type >> 8) & 0xff;
    out[1] = type & 0xff;
    out[2] = (data.length >> 8) & 0xff;
    out[3] = data.length & 0xff;
    out.set(data, 4);
    return out;
}

/** Encode the SNI server_name_list body (RFC 6066 §3). */
function encodeServerNameList(serverName: string): Uint8Array {
    const nameBytes = new TextEncoder().encode(serverName);
    if (nameBytes.length > 0xffff) {
        throw new TlsHandshakeError("client_hello", {
            cause: new Error("SNI server_name exceeds 65535 bytes"),
        });
    }
    // server_name_list: length(2) + entries. Each entry: type(1)=0 + length(2) + name.
    const entry = new Uint8Array(1 + 2 + nameBytes.length);
    entry[0] = 0; // host_name
    entry[1] = (nameBytes.length >> 8) & 0xff;
    entry[2] = nameBytes.length & 0xff;
    entry.set(nameBytes, 3);

    const out = new Uint8Array(2 + entry.length);
    out[0] = (entry.length >> 8) & 0xff;
    out[1] = entry.length & 0xff;
    out.set(entry, 2);
    return out;
}

/** Encode the supported_versions extension body for the client (RFC 8446 §4.2.1). */
function encodeSupportedVersionsClient(versions: readonly ProtocolVersion[]): Uint8Array {
    const out = new Uint8Array(1 + versions.length * 2);
    out[0] = (versions.length * 2) & 0xff;
    for (let i = 0; i < versions.length; i++) {
        const version = versions[i];
        if (version === undefined) {
            throw new TlsHandshakeError("client_hello", {
                cause: new Error(`supported version at index ${i} is missing`),
            });
        }
        const wire = version.wire;
        out[1 + i * 2] = (wire >> 8) & 0xff;
        out[1 + i * 2 + 1] = wire & 0xff;
    }
    return out;
}

/**
 * Encode the key_share extension body for the client (RFC 8446 §4.2.8).
 *
 * When GREASE is enabled, a GREASE key-share entry (group 0x0a0a) with a random
 * key precedes the real groups — matching real-browser ClientHellos.
 */
function encodeKeyShareClient(config: ClientHelloConfig, keyPairs: readonly KeyPair[]): Uint8Array {
    // client_shares: length(2) + entries. Each: group(2) + len(2) + key_exchange.
    const greaseEntry = config.grease ? 2 + 2 + GREASE_KEY_LENGTH : 0;
    let entriesLen = greaseEntry;
    for (const kp of keyPairs) {
        entriesLen += 2 + 2 + kp.publicKey.length;
    }
    const out = new Uint8Array(2 + entriesLen);
    out[0] = (entriesLen >> 8) & 0xff;
    out[1] = entriesLen & 0xff;
    let o = 2;
    if (config.grease) {
        // GREASE key-share group (0x0a0a) with a random key of GREASE_KEY_LENGTH bytes.
        out[o++] = (GREASE_CIPHER_WIRE >> 8) & 0xff;
        out[o++] = GREASE_CIPHER_WIRE & 0xff;
        out[o++] = (GREASE_KEY_LENGTH >> 8) & 0xff;
        out[o++] = GREASE_KEY_LENGTH & 0xff;
        out.set(crypto.randomBytes(GREASE_KEY_LENGTH), o);
        o += GREASE_KEY_LENGTH;
    }
    for (const kp of keyPairs) {
        const groupWire = namedGroupToWire(kp.algorithm);
        out[o++] = (groupWire >> 8) & 0xff;
        out[o++] = groupWire & 0xff;
        out[o++] = (kp.publicKey.length >> 8) & 0xff;
        out[o++] = kp.publicKey.length & 0xff;
        out.set(kp.publicKey, o);
        o += kp.publicKey.length;
    }
    return out;
}

/** Encode the signature_algorithms extension body (RFC 8446 §4.2.3). */
function encodeSignatureAlgorithms(algorithms: readonly SignatureScheme[]): Uint8Array {
    const out = new Uint8Array(2 + algorithms.length * 2);
    out[0] = ((algorithms.length * 2) >> 8) & 0xff;
    out[1] = (algorithms.length * 2) & 0xff;
    for (let i = 0; i < algorithms.length; i++) {
        const scheme = algorithms[i];
        if (scheme === undefined) {
            throw new TlsHandshakeError("client_hello", {
                cause: new Error(`signature algorithm at index ${i} is missing`),
            });
        }
        const wire = signatureSchemeToWire(scheme);
        out[2 + i * 2] = (wire >> 8) & 0xff;
        out[2 + i * 2 + 1] = wire & 0xff;
    }
    return out;
}

/** Encode the ALPN extension body (RFC 7301). */
function encodeAlpn(protocols: readonly string[]): Uint8Array {
    let entriesLen = 0;
    for (const proto of protocols) {
        const encoded = new TextEncoder().encode(proto);
        if (encoded.length === 0 || encoded.length > 0xff) {
            throw new TlsHandshakeError("client_hello", {
                cause: new Error(`ALPN protocol must be 1..255 bytes: "${proto}"`),
            });
        }
        entriesLen += 1 + encoded.length;
    }
    const out = new Uint8Array(2 + entriesLen);
    out[0] = (entriesLen >> 8) & 0xff;
    out[1] = entriesLen & 0xff;
    let o = 2;
    for (const proto of protocols) {
        const encoded = new TextEncoder().encode(proto);
        out[o++] = encoded.length & 0xff;
        out.set(encoded, o);
        o += encoded.length;
    }
    return out;
}

// ---------------------------------------------------------------------------
// Pre-shared key extension: binder computation (RFC 8446 §4.2.11).
// ---------------------------------------------------------------------------

/**
 * Build the pre_shared_key extension with valid binders (RFC 8446 §4.2.11.2).
 *
 * Two-phase construction:
 *   1. Serialize the ClientHello body with a truncated PSK extension that
 *      contains only the identities (binders field length = 0). This truncated
 *      body is the message the binder authenticates. It MUST use the same
 *      `random` that is emitted on the wire — the server recomputes the binder
 *      over the random it received, so any mismatch fails verification.
 *   2. Compute binder = HMAC(binder_key, Transcript-Hash(truncated-CH)).
 *   3. Emit the full PSK extension with binder entries.
 *
 * @param config    ClientHello config (extension order, cipher suites, etc.).
 * @param keyPairs  (EC)DHE key pairs for the key_share extension.
 * @param random    The ClientHello random — threaded in from buildClientHello
 *                  so the binder authenticates over the exact bytes on the wire.
 * @param psk       PSK parameters (identity, ticket age, resumption secret).
 */
function buildPskExtensionWithBinder(
    config: ClientHelloConfig,
    keyPairs: readonly KeyPair[],
    random: Uint8Array,
    psk: ClientHelloPskParams,
): Uint8Array {
    const hash = hashFor(psk.cipherSuite);
    const earlySecret = deriveEarlySecretFromPsk(psk.psk, hash);
    const binderKey = deriveBinderKey(earlySecret, hash);

    // Phase 1: build the truncated extension (identities only, no binders).
    const truncatedPskBody = encodePreSharedKeyIdentities(psk);
    const truncatedPskExt = wrapExtension(ExtensionType.PRE_SHARED_KEY, truncatedPskBody);

    // Build a fake extensions list where the PSK extension is truncated, so we
    // can serialize the full ClientHello body (with the shared random) and hash
    // it. The early_data extension, if present, is included in the transcript.
    const truncatedParts: Uint8Array[] = [];
    for (const type of config.extensionOrder) {
        if (type === ExtensionType.PRE_SHARED_KEY) {
            truncatedParts.push(truncatedPskExt);
            continue;
        }
        const body = encodeExtensionBody(type, config, keyPairs);
        truncatedParts.push(wrapExtension(type, body));
    }
    // Include early_data in the binder transcript if offered (it follows PSK
    // in real-client layouts and authenticates alongside it).
    if (psk.offerEarlyData) {
        truncatedParts.push(wrapExtension(ExtensionType.EARLY_DATA, new Uint8Array(0)));
    }
    let truncatedTotal = 0;
    for (const p of truncatedParts) {
        truncatedTotal += p.length;
    }
    const truncatedExtensions = new Uint8Array(truncatedTotal);
    let to = 0;
    for (const p of truncatedParts) {
        truncatedExtensions.set(p, to);
        to += p.length;
    }

    // Serialize the truncated ClientHello body using the SAME random as the
    // wire message. This is the core of the fix: previously this function
    // generated its own random, so the binder authenticated over bytes the
    // server never saw.
    const truncatedHello = serializeClientHelloBody(config, keyPairs, truncatedExtensions, random);

    // Phase 2: compute binder over the truncated transcript.
    const binder = computeBinder(binderKey, truncatedHello, hash);

    // Phase 3: emit the full PSK extension with identities + binders.
    const fullPskBody = encodePreSharedKey(psk, [binder]);
    return wrapExtension(ExtensionType.PRE_SHARED_KEY, fullPskBody);
}

/**
 * Serialize the ClientHello body (everything after the 4-byte handshake header)
 * given a pre-built extensions block and a caller-provided random.
 *
 * Shared by binder computation so the transcript uses the exact random emitted
 * on the wire. RFC 8446 §4.2.11.2 requires the binder to authenticate over the
 * same ClientHello (including its random) that the server receives.
 *
 * Exposed (exported) so the binder regression test can recompute the binder
 * over the same random and assert consistency.
 *
 * @param config     ClientHello config.
 * @param keyPairs   (EC)DHE key pairs (passed for signature parity; unused).
 * @param extensions Pre-serialized extensions block (already in order).
 * @param random     The ClientHello random to embed — caller-provided so binder
 *                   transcript and wire message stay consistent.
 */
export function serializeClientHelloBody(
    config: ClientHelloConfig,
    _keyPairs: readonly KeyPair[],
    extensions: Uint8Array,
    random: Uint8Array,
): Uint8Array {
    const sessionId = new Uint8Array(0);
    const compressionMethods = new Uint8Array([0x00]);

    const cipherWires: number[] = config.cipherSuites.map((suite, i) => {
        if (suite === undefined) {
            throw new TlsHandshakeError("client_hello", {
                cause: new Error(`cipher suite at index ${i} is missing`),
            });
        }
        return cipherSuiteToWire(suite);
    });
    if (config.grease && (cipherWires.length === 0 || cipherWires[0] !== GREASE_CIPHER_WIRE)) {
        cipherWires.unshift(GREASE_CIPHER_WIRE);
    }
    const cipherSuitesBytes = new Uint8Array(cipherWires.length * 2);
    for (let i = 0; i < cipherWires.length; i++) {
        const wire = cipherWires[i];
        if (wire === undefined) {
            throw new TlsHandshakeError("client_hello", {
                cause: new Error(`cipher suite wire at index ${i} is missing`),
            });
        }
        cipherSuitesBytes[i * 2] = (wire >> 8) & 0xff;
        cipherSuitesBytes[i * 2 + 1] = wire & 0xff;
    }

    const bodyLen =
        2 + random.length + 1 + sessionId.length +
        2 + cipherSuitesBytes.length +
        1 + compressionMethods.length +
        2 + extensions.length;

    const body = new Uint8Array(bodyLen);
    let o = 0;
    body[o++] = (TLS_1_2_WIRE_VERSION >> 8) & 0xff;
    body[o++] = TLS_1_2_WIRE_VERSION & 0xff;
    body.set(random, o);
    o += random.length;
    body[o++] = sessionId.length & 0xff;
    body.set(sessionId, o);
    o += sessionId.length;
    body[o++] = (cipherSuitesBytes.length >> 8) & 0xff;
    body[o++] = cipherSuitesBytes.length & 0xff;
    body.set(cipherSuitesBytes, o);
    o += cipherSuitesBytes.length;
    body[o++] = compressionMethods.length & 0xff;
    body.set(compressionMethods, o);
    o += compressionMethods.length;
    body[o++] = (extensions.length >> 8) & 0xff;
    body[o++] = extensions.length & 0xff;
    body.set(extensions, o);

    return body;
}

/**
 * Encode only the identities portion of the pre_shared_key extension body.
 *
 * Layout: identities_len(2) + identity { identity_len(2) || identity ||
 * obfuscated_ticket_age(4) }.
 *
 * This is the "truncated" PSK body used to compute the binder transcript: it
 * contains everything the binder authenticates *except* the binders themselves.
 */
function encodePreSharedKeyIdentities(psk: ClientHelloPskParams): Uint8Array {
    const identityLen = 2 + psk.identity.length + 4;
    const identitiesLen = 2 + identityLen;
    const out = new Uint8Array(identitiesLen);
    let o = 0;
    out[o++] = (identityLen >> 8) & 0xff;
    out[o++] = identityLen & 0xff;
    out[o++] = (psk.identity.length >> 8) & 0xff;
    out[o++] = psk.identity.length & 0xff;
    out.set(psk.identity, o);
    o += psk.identity.length;
    // obfuscated_ticket_age: uint32 milliseconds.
    out[o++] = (psk.obfuscatedTicketAge >>> 24) & 0xff;
    out[o++] = (psk.obfuscatedTicketAge >>> 16) & 0xff;
    out[o++] = (psk.obfuscatedTicketAge >>> 8) & 0xff;
    out[o++] = psk.obfuscatedTicketAge & 0xff;
    return out;
}

/**
 * Encode the full pre_shared_key extension body: identities + binders.
 *
 * Layout: identities_len(2) + identities || binders_len(2) +
 * binder { binder_len(1) || binder_entry }.
 *
 * `binders` carries one binder per offered identity (computed by
 * buildPskExtensionWithBinder over the truncated ClientHello).
 */
function encodePreSharedKey(psk: ClientHelloPskParams, binders: readonly Uint8Array[]): Uint8Array {
    const identities = encodePreSharedKeyIdentities(psk);
    let bindersLen = 0;
    for (const b of binders) {
        bindersLen += 1 + b.length;
    }
    const out = new Uint8Array(2 + identities.length + 2 + bindersLen);
    let o = 0;
    // identities_len(2) + identities.
    out[o++] = (identities.length >> 8) & 0xff;
    out[o++] = identities.length & 0xff;
    out.set(identities, o);
    o += identities.length;
    // binders_len(2) + binders.
    out[o++] = (bindersLen >> 8) & 0xff;
    out[o++] = bindersLen & 0xff;
    for (const b of binders) {
        out[o++] = b.length & 0xff;
        out.set(b, o);
        o += b.length;
    }
    return out;
}
