/**
 * ClientHello construction (RFC 8446 §4.2).
 *
 * Serializes the client's opening handshake message: legacy version + random +
 * session id + cipher suites + the extensions that actually drive TLS 1.3
 * negotiation (SNI, supported_versions, key_share, signature_algorithms, ALPN).
 * This is the only place that knows the ClientHello wire layout; the rest of the
 * handshake module only consumes the bytes it produces.
 */

import { crypto } from "@browsercore/crypto";
import type { CipherSuite, ClientHelloConfig, KeyPair, ProtocolVersion, SignatureScheme } from "../types.js";
import { TlsHandshakeError } from "../errors.js";
import { assertNever } from "../utils.js";
import { ExtensionType, namedGroupToWire, signatureSchemeToWire } from "../extensions/extensions.js";
import { HandshakeType } from "./handshake-types.js";

/** TLS 1.2 wire version used as legacy_version in TLS 1.3 records/handshakes. */
const TLS_1_2_WIRE_VERSION = 0x0303;

/** Cipher suite IANA wire values (subset used by TLS 1.3). */
function cipherSuiteToWire(suite: CipherSuite): number {
    switch (suite) {
        case "TLS_AES_128_GCM_SHA256":
            return 0x1301;
        case "TLS_AES_256_GCM_SHA384":
            return 0x1302;
        case "TLS_CHACHA20_POLY1305_SHA256":
            return 0x1303;
        case "TLS_AES_128_CCM_SHA256":
            return 0x1304;
        default:
            // All four TLS 1.3 suites are covered; this is unreachable but keeps
            // the switch exhaustive if CipherSuite is ever extended.
            return assertNever(suite);
    }
}

/**
 * Build a ClientHello handshake message from the given config.
 *
 * Serializes the full handshake message (header + body) with extensions for SNI,
 * supported_versions, key_share, signature_algorithms, and (optionally) ALPN.
 * The (EC)DHE public keys come from `keyPairs` (already generated by the caller
 * via @browsercore/crypto).
 */
export function buildClientHello(config: ClientHelloConfig, keyPairs: readonly KeyPair[]): Uint8Array {
    const random = crypto.randomBytes(32);
    const sessionId = new Uint8Array(0);
    const compressionMethods = new Uint8Array([0x00]);

    const extensions = buildClientHelloExtensions(config, keyPairs);

    // Body length: version(2) + random(32) + session_id_len(1) + session_id +
    //   cipher_suites_len(2) + cipher_suites + compression_len(1) + compression +
    //   extensions_len(2) + extensions.
    const cipherSuitesBytes = new Uint8Array(config.cipherSuites.length * 2);
    for (let i = 0; i < config.cipherSuites.length; i++) {
        const suite = config.cipherSuites[i];
        if (suite === undefined) {
            throw new TlsHandshakeError("client_hello", {
                cause: new Error(`cipher suite at index ${i} is missing`),
            });
        }
        const wire = cipherSuiteToWire(suite);
        cipherSuitesBytes[i * 2] = (wire >> 8) & 0xff;
        cipherSuitesBytes[i * 2 + 1] = wire & 0xff;
    }

    const bodyLen =
        2 + random.length + 1 + sessionId.length +
        2 + cipherSuitesBytes.length +
        1 + compressionMethods.length +
        2 + extensions.length;

    // Handshake header: msg_type(1) + length(24-bit) + body.
    const message = new Uint8Array(1 + 3 + bodyLen);
    let o = 0;
    message[o++] = HandshakeType.CLIENT_HELLO;
    message[o++] = (bodyLen >> 16) & 0xff;
    message[o++] = (bodyLen >> 8) & 0xff;
    message[o++] = bodyLen & 0xff;

    // legacy_version = 0x0303 (TLS 1.2 for middlebox compatibility).
    message[o++] = (TLS_1_2_WIRE_VERSION >> 8) & 0xff;
    message[o++] = TLS_1_2_WIRE_VERSION & 0xff;
    message.set(random, o);
    o += random.length;

    // Session ID (length-prefixed; empty for TLS 1.3).
    message[o++] = sessionId.length & 0xff;
    message.set(sessionId, o);
    o += sessionId.length;

    // Cipher suites (length-prefixed).
    message[o++] = (cipherSuitesBytes.length >> 8) & 0xff;
    message[o++] = cipherSuitesBytes.length & 0xff;
    message.set(cipherSuitesBytes, o);
    o += cipherSuitesBytes.length;

    // Compression methods (length-prefixed; single null).
    message[o++] = compressionMethods.length & 0xff;
    message.set(compressionMethods, o);
    o += compressionMethods.length;

    // Extensions (length-prefixed).
    message[o++] = (extensions.length >> 8) & 0xff;
    message[o++] = extensions.length & 0xff;
    message.set(extensions, o);

    return message;
}

/**
 * Serialize the extensions block for a ClientHello. Each extension is
 * type(2) || data_len(2) || data, all under a single length-prefix.
 */
function buildClientHelloExtensions(config: ClientHelloConfig, keyPairs: readonly KeyPair[]): Uint8Array {
    const parts: readonly Uint8Array[] = [
        wrapExtension(ExtensionType.SERVER_NAME, encodeServerNameList(config.serverName)),
        wrapExtension(ExtensionType.SUPPORTED_VERSIONS, encodeSupportedVersionsClient(config.supportedVersions)),
        wrapExtension(ExtensionType.KEY_SHARE, encodeKeyShareClient(keyPairs)),
        wrapExtension(ExtensionType.SIGNATURE_ALGORITHMS, encodeSignatureAlgorithms(config.signatureAlgorithms)),
        ...(config.alpnProtocols !== undefined && config.alpnProtocols.length > 0
            ? [wrapExtension(ExtensionType.APPLICATION_LAYER_PROTOCOL_NEGOTIATION, encodeAlpn(config.alpnProtocols))]
            : []),
    ];

    let total = 0;
    for (const p of parts) {
        total += p.length;
    }
    const out = new Uint8Array(total);
    let o = 0;
    for (const p of parts) {
        out.set(p, o);
        o += p.length;
    }
    return out;
}

/** Wrap an extension body with its type + length prefix. */
function wrapExtension(type: ExtensionType, data: Uint8Array): Uint8Array {
    const out = new Uint8Array(2 + 2 + data.length);
    out[0] = (type >> 8) & 0xff;
    out[1] = type & 0xff;
    out[2] = (data.length >> 8) & 0xff;
    out[3] = data.length & 0xff;
    out.set(data, 4);
    return out;
}

/** Encode the SNI server_name_list body (RFC 6066 §3). */
function encodeServerNameList(serverName: string): Uint8Array {
    const nameBytes = new TextEncoder().encode(serverName);
    if (nameBytes.length > 0xffff) {
        throw new TlsHandshakeError("client_hello", {
            cause: new Error("SNI server_name exceeds 65535 bytes"),
        });
    }
    // server_name_list: length(2) + entries. Each entry: type(1)=0 + length(2) + name.
    const entry = new Uint8Array(1 + 2 + nameBytes.length);
    entry[0] = 0; // host_name
    entry[1] = (nameBytes.length >> 8) & 0xff;
    entry[2] = nameBytes.length & 0xff;
    entry.set(nameBytes, 3);

    const out = new Uint8Array(2 + entry.length);
    out[0] = (entry.length >> 8) & 0xff;
    out[1] = entry.length & 0xff;
    out.set(entry, 2);
    return out;
}

/** Encode the supported_versions extension body for the client (RFC 8446 §4.2.1). */
function encodeSupportedVersionsClient(versions: readonly ProtocolVersion[]): Uint8Array {
    const out = new Uint8Array(1 + versions.length * 2);
    out[0] = (versions.length * 2) & 0xff;
    for (let i = 0; i < versions.length; i++) {
        const version = versions[i];
        if (version === undefined) {
            throw new TlsHandshakeError("client_hello", {
                cause: new Error(`supported version at index ${i} is missing`),
            });
        }
        const wire = version.wire;
        out[1 + i * 2] = (wire >> 8) & 0xff;
        out[1 + i * 2 + 1] = wire & 0xff;
    }
    return out;
}

/** Encode the key_share extension body for the client (RFC 8446 §4.2.8). */
function encodeKeyShareClient(keyPairs: readonly KeyPair[]): Uint8Array {
    // client_shares: length(2) + entries. Each: group(2) + len(2) + key_exchange.
    let entriesLen = 0;
    for (const kp of keyPairs) {
        entriesLen += 2 + 2 + kp.publicKey.length;
    }
    const out = new Uint8Array(2 + entriesLen);
    out[0] = (entriesLen >> 8) & 0xff;
    out[1] = entriesLen & 0xff;
    let o = 2;
    for (const kp of keyPairs) {
        // KeyPair.algorithm is a subset of NamedGroup ("x25519" | "secp256r1" |
        // "secp384r1"), so it is assignable without a cast — the previous
        // `as NamedGroup` only suppressed that sound widening.
        const groupWire = namedGroupToWire(kp.algorithm);
        out[o++] = (groupWire >> 8) & 0xff;
        out[o++] = groupWire & 0xff;
        out[o++] = (kp.publicKey.length >> 8) & 0xff;
        out[o++] = kp.publicKey.length & 0xff;
        out.set(kp.publicKey, o);
        o += kp.publicKey.length;
    }
    return out;
}

/** Encode the signature_algorithms extension body (RFC 8446 §4.2.3). */
function encodeSignatureAlgorithms(algorithms: readonly SignatureScheme[]): Uint8Array {
    const out = new Uint8Array(2 + algorithms.length * 2);
    out[0] = ((algorithms.length * 2) >> 8) & 0xff;
    out[1] = (algorithms.length * 2) & 0xff;
    for (let i = 0; i < algorithms.length; i++) {
        const scheme = algorithms[i];
        if (scheme === undefined) {
            throw new TlsHandshakeError("client_hello", {
                cause: new Error(`signature algorithm at index ${i} is missing`),
            });
        }
        const wire = signatureSchemeToWire(scheme);
        out[2 + i * 2] = (wire >> 8) & 0xff;
        out[2 + i * 2 + 1] = wire & 0xff;
    }
    return out;
}

/** Encode the ALPN extension body (RFC 7301). */
function encodeAlpn(protocols: readonly string[]): Uint8Array {
    let entriesLen = 0;
    for (const proto of protocols) {
        const encoded = new TextEncoder().encode(proto);
        if (encoded.length === 0 || encoded.length > 0xff) {
            throw new TlsHandshakeError("client_hello", {
                cause: new Error(`ALPN protocol must be 1..255 bytes: "${proto}"`),
            });
        }
        entriesLen += 1 + encoded.length;
    }
    const out = new Uint8Array(2 + entriesLen);
    out[0] = (entriesLen >> 8) & 0xff;
    out[1] = entriesLen & 0xff;
    let o = 2;
    for (const proto of protocols) {
        const encoded = new TextEncoder().encode(proto);
        out[o++] = encoded.length & 0xff;
        out.set(encoded, o);
        o += encoded.length;
    }
    return out;
}
