/**
 * ClientHello construction (RFC 8446 §4.2).
 *
 * Serializes the client's opening handshake message: legacy version + random +
 * session id + cipher suites + the extensions that actually drive TLS 1.3
 * negotiation (SNI, supported_versions, key_share, signature_algorithms, ALPN).
 * This is the only place that knows the ClientHello wire layout; the rest of the
 * handshake module only consumes the bytes it produces.
 */

import type { CryptoProvider } from "@browsercore/crypto";
import type {
    CipherSuite,
    ClientHelloConfig,
    KeyPair,
    NamedGroup,
    ProtocolVersion,
    SignatureScheme,
} from "../types.js";
import { TlsHandshakeError } from "../errors.js";
import { ExtensionType, isGreaseValue, namedGroupToWire, signatureSchemeToWire } from "../extensions/extensions.js";
export { isGreaseValue } from "../extensions/extensions.js";
import { HandshakeType } from "./handshake-types.js";
import { CIPHER_SUITE_CODES } from "../iana/index.js";
import { computePaddingExtensionBody } from "../record/record-padding.js";

/** TLS 1.2 wire version used as legacy_version in TLS 1.3 records/handshakes. */
const TLS_1_2_WIRE_VERSION = 0x0303;

/**
 * The 16 GREASE sentinels reserved by RFC 8701 §2 (0x?a?a set).
 *
 * Real browsers pick one of these uniformly at random per connection and reuse
 * it across every GREASE slot in that ClientHello (cipher suite, extension
 * type, key-share group). `generateGreaseValue` draws from here; `isGreaseValue`
 * validates against it. Single source of truth for the reserved set.
 */
export const GREASE_VALUES: readonly number[] = Object.freeze([
    0x0a0a, 0x1a1a, 0x2a2a, 0x3a3a,
    0x4a4a, 0x5a5a, 0x6a6a, 0x7a7a,
    0x8a8a, 0x9a9a, 0xaaaa, 0xbaba,
    0xcaca, 0xdada, 0xeaea, 0xfafa,
]);

/**
 * Pick a uniform random GREASE value.
 *
 * The random source is a REQUIRED parameter (no singleton fallback) so the
 * caller — which already holds the injected CryptoProvider — controls every
 * source of randomness. Tests pin it deterministically; production passes a
 * crypto-backed uniform [0,1) so traffic never depends on Math.random.
 */
export function generateGreaseValue(random: () => number): number {
    const index = Math.floor(random() * GREASE_VALUES.length);
    const value = GREASE_VALUES[index];
    // GREASE_VALUES.length === 16 is a constant; this is an invariant guard.
    /* v8 ignore next 3 */
    if (value === undefined) {
        throw new TlsHandshakeError("client_hello", {
            cause: new Error("generateGreaseValue: unreachable — GREASE_VALUES is empty"),
        });
    }
    return value;
}

/**
 * Length (bytes) of the key-exchange blob we emit for a GREASE key-share entry.
 * Matches X25519 so the GREASE entry is indistinguishable in size from a real one.
 */
const GREASE_KEY_LENGTH = 32;

/**
 * Cipher suite IANA wire values.
 *
 * Covers every suite the shipped browser profiles offer: the four TLS 1.3 AEAD
 * suites (the only ones a TLS 1.3 handshake can *negotiate*) plus the TLS 1.2
 * suites and the GREASE placeholder that real Chrome places in the *offered*
 * ClientHello list for middlebox compatibility. Values come from the canonical
 * IANA table in `../iana/cipher-suites.ts`.
 */
export function cipherSuiteToWire(suite: CipherSuite): number {
    const code = CIPHER_SUITE_CODES[suite];
    if (code === undefined) {
        throw new TlsHandshakeError("client_hello", {
            cause: new Error(`unknown cipher suite: ${suite}`),
        });
    }
    return code;
}

/**
 * Build a ClientHello handshake message from the given config.
 *
 * Serializes the full handshake message (header + body) with extensions for SNI,
 * supported_versions, key_share, signature_algorithms, and (optionally) ALPN.
 * The (EC)DHE public keys come from `keyPairs` (already generated by the caller
 * via @browsercore/crypto).
 *
 * When `config.grease` is enabled, exactly one random 0x?a?a sentinel is drawn
 * per call (from `random`) and reused across the leading cipher suite, the
 * leading extension type, and the leading key-share group — matching real
 * Chrome behavior (RFC 8701). The `random` source and `provider` are required
 * (no singleton fallback) so callers control all randomness; tests pin
 * `random` for a deterministic sentinel.
 */
export function buildClientHello(
    config: ClientHelloConfig,
    keyPairs: readonly KeyPair[],
    random: () => number,
    provider: CryptoProvider,
    cookie?: Uint8Array,
): Uint8Array {
    const greaseValue = config.grease ? generateGreaseValue(random) : 0;

    const randomBytes = provider.randomBytes(32);
    const sessionId = new Uint8Array(0);
    const compressionMethods = new Uint8Array([0x00]);

    const cipherWires: number[] = config.cipherSuites.map((suite, i) => {
        if (suite === undefined) {
            throw new TlsHandshakeError("client_hello", {
                cause: new Error(`cipher suite at index ${i} is missing`),
            });
        }
        return cipherSuiteToWire(suite);
    });
    if (cipherWires.length > 0 && config.grease) {
        // The length guard above narrows the element to `number`, so this read
        // satisfies noUncheckedIndexedAccess without a non-null assertion.
        const first = cipherWires[0];
        if (first !== undefined && isGreaseValue(first)) {
            cipherWires[0] = greaseValue;
        } else {
            cipherWires.unshift(greaseValue);
        }
    }
    const cipherSuitesBytes = new Uint8Array(cipherWires.length * 2);
    for (let i = 0; i < cipherWires.length; i++) {
        const wire = cipherWires[i];
        /* v8 ignore next 3 */
        if (wire === undefined) {
            throw new TlsHandshakeError("client_hello", {
                cause: new Error(`cipher suite wire at index ${i} is missing`),
            });
        }
        cipherSuitesBytes[i * 2] = (wire >> 8) & 0xff;
        cipherSuitesBytes[i * 2 + 1] = wire & 0xff;
    }

    // Build base extensions (with zero padding) to measure the ClientHello size.
    const baseExtensions = buildClientHelloExtensions(config, keyPairs, greaseValue, provider, cookie);

    // Record padding (RFC 7685 / RFC 8446 §4.1.2): measure the base ClientHello
    // (extensions built with zero padding), then rebuild with the computed
    // padding body so the total message hits `config.recordPadding` bytes.
    let finalExtensions = baseExtensions;
    if (config.recordPadding !== undefined) {
        const bodyLenProbe =
            2 + randomBytes.length + 1 + sessionId.length +
            2 + cipherSuitesBytes.length +
            1 + compressionMethods.length +
            2 + baseExtensions.length;
        const probeMessageSize = 4 + bodyLenProbe;
        const paddingAmount = computePaddingExtensionBody(probeMessageSize, config);
        if (paddingAmount > 0) {
            finalExtensions = buildClientHelloExtensions(config, keyPairs, greaseValue, provider, cookie, paddingAmount);
        }
    }

    const bodyLen =
        2 + randomBytes.length + 1 + sessionId.length +
        2 + cipherSuitesBytes.length +
        1 + compressionMethods.length +
        2 + finalExtensions.length;

    const message = new Uint8Array(1 + 3 + bodyLen);
    let o = 0;
    message[o++] = HandshakeType.CLIENT_HELLO;
    message[o++] = (bodyLen >> 16) & 0xff;
    message[o++] = (bodyLen >> 8) & 0xff;
    message[o++] = bodyLen & 0xff;
    message[o++] = (TLS_1_2_WIRE_VERSION >> 8) & 0xff;
    message[o++] = TLS_1_2_WIRE_VERSION & 0xff;
    message.set(randomBytes, o);
    o += randomBytes.length;
    message[o++] = sessionId.length & 0xff;
    message.set(sessionId, o);
    o += sessionId.length;
    message[o++] = (cipherSuitesBytes.length >> 8) & 0xff;
    message[o++] = cipherSuitesBytes.length & 0xff;
    message.set(cipherSuitesBytes, o);
    o += cipherSuitesBytes.length;
    message[o++] = compressionMethods.length & 0xff;
    message.set(compressionMethods, o);
    o += compressionMethods.length;
    message[o++] = (finalExtensions.length >> 8) & 0xff;
    message[o++] = finalExtensions.length & 0xff;
    message.set(finalExtensions, o);

    return message;
}

function buildClientHelloExtensions(
    config: ClientHelloConfig,
    keyPairs: readonly KeyPair[],
    greaseValue: number,
    provider: CryptoProvider,
    cookie?: Uint8Array,
    paddingAmount = 0,
): Uint8Array {
    const order = config.grease
        ? [greaseValue, ...config.extensionOrder]
        : [...config.extensionOrder];

    const parts: Uint8Array[] = [];
    let paddingInOrder = false;
    for (const type of order) {
        if (type === ExtensionType.PADDING) {
            paddingInOrder = true;
        }
        const body = encodeExtensionBody(type, config, keyPairs, greaseValue, provider, paddingAmount);
        // Unknown extension types return undefined (no encoder). Skip them so
        // they don't bloat the ClientHello. GREASE, padding, SCT, EMS, etc. all
        // legitimately produce zero-length bodies — they must still be emitted.
        if (body === undefined) { continue; }
        parts.push(wrapExtension(type, body));
    }

    // RFC 8446 §4.2.2: when the server sent a cookie in HelloRetryRequest, the
    // client MUST echo it in the new ClientHello. The cookie extension is
    // appended after the profile's extensions so the original fingerprint order
    // is preserved.
    if (cookie !== undefined && cookie.length > 0) {
        parts.push(wrapExtension(ExtensionType.COOKIE, encodeCookie(cookie)));
    }

    // When padding is needed and the PADDING extension was not in the profile's
    // extension order, append it at the very end (real browsers place it last).
    if (!paddingInOrder && paddingAmount > 0) {
        parts.push(wrapExtension(ExtensionType.PADDING, new Uint8Array(paddingAmount)));
    }

    let total = 0;
    for (const p of parts) {
        total += p.length;
    }
    const out = new Uint8Array(total);
    let o = 0;
    for (const p of parts) {
        out.set(p, o);
        o += p.length;
    }
    return out;
}

function encodeExtensionBody(
    type: number,
    config: ClientHelloConfig,
    keyPairs: readonly KeyPair[],
    greaseValue: number,
    provider: CryptoProvider,
    paddingAmount = 0,
): Uint8Array | undefined {
    switch (type) {
        case ExtensionType.SERVER_NAME:
            return encodeServerNameList(config.serverName);
        case ExtensionType.STATUS_REQUEST:
            return encodeStatusRequest();
        case ExtensionType.SUPPORTED_GROUPS:
            return encodeSupportedGroups(config.keyShareGroups);
        case ExtensionType.EC_POINT_FORMATS:
            return encodeEcPointFormats(config.ecPointFormats);
        case ExtensionType.SIGNATURE_ALGORITHMS:
            return encodeSignatureAlgorithms(config.signatureAlgorithms);
        case ExtensionType.APPLICATION_LAYER_PROTOCOL_NEGOTIATION:
            return config.alpnProtocols !== undefined && config.alpnProtocols.length > 0
                ? encodeAlpn(config.alpnProtocols)
                : new Uint8Array(0);
        case ExtensionType.APPLICATION_SETTINGS:
            return encodeApplicationSettings(config.alpnProtocols);
        case ExtensionType.APPLICATION_SETTINGS_OLD:
            return encodeApplicationSettings(config.alpnProtocols);
        case ExtensionType.ENCRYPTED_CLIENT_HELLO:
            // No HPKE keys for real ECH; emit an empty body as a placeholder.
            // The fetch layer filters this out of extensionOrder before connecting.
            return new Uint8Array(0);
        case ExtensionType.SIGNED_CERTIFICATE_TIMESTAMP:
            return new Uint8Array(0);
        case ExtensionType.EXTENDED_MASTER_SECRET:
            return new Uint8Array(0);
        case ExtensionType.COMPRESS_CERTIFICATE:
            return encodeCompressCertificate(config.compressCertificateAlgorithms);
        case ExtensionType.SESSION_TICKET:
            return new Uint8Array(0);
        case ExtensionType.PRE_SHARED_KEY:
            return new Uint8Array(0);
        case ExtensionType.SUPPORTED_VERSIONS:
            return encodeSupportedVersionsClient(config.supportedVersions);
        case ExtensionType.PSK_KEY_EXCHANGE_MODES:
            return encodePskKeyExchangeModes();
        case ExtensionType.KEY_SHARE:
            return encodeKeyShareClient(config, keyPairs, greaseValue, provider);
        case ExtensionType.PADDING:
            // RFC 7685: the body is a run of zero bytes. The length is computed
            // by the caller via computePaddingExtensionBody and threaded through.
            return new Uint8Array(paddingAmount);
        case ExtensionType.RENEGOTIATION_INFO:
            return encodeRenegotiationInfo();
        default:
            if (isGreaseValue(type)) {
                return new Uint8Array(0);
            }
            // Unknown extension type (e.g. extended_random 0x1c, or 0x22 in the
            // firefox-128 profile): return undefined so the caller skips it.
            return undefined;
    }
}

function encodeSupportedGroups(groups: readonly NamedGroup[]): Uint8Array {
    // Emit ALL offered groups verbatim — including post-quantum hybrids like
    // X25519MLKEM768 (0x11ec). They must appear in supported_groups for the
    // JA3/JA4 fingerprint to match real browsers. The crypto backend falls back
    // to the classical X25519 half if a server actually selects a hybrid.
    const out = new Uint8Array(2 + groups.length * 2);
    out[0] = ((groups.length * 2) >> 8) & 0xff;
    out[1] = (groups.length * 2) & 0xff;
    for (let i = 0; i < groups.length; i++) {
        const group = groups[i];
        if (group === undefined) {
            throw new TlsHandshakeError("client_hello", {
                cause: new Error(`supported group at index ${i} is missing`),
            });
        }
        const wire = namedGroupToWire(group);
        out[2 + i * 2] = (wire >> 8) & 0xff;
        out[2 + i * 2 + 1] = wire & 0xff;
    }
    return out;
}

/** Default EC point formats: uncompressed (0x00) only. */
const DEFAULT_EC_POINT_FORMATS: readonly number[] = [0x00];

/**
 * Encode the `ec_point_formats` extension body from config.
 *
 * Defaults to `[0x00]` (uncompressed) when the profile omits the field. Real
 * browsers list `[0x01, 0x00]` (ansiX962_compressed_prime + uncompressed) — the
 * exact ordering is a fingerprint signal, so it flows from the profile.
 */
function encodeEcPointFormats(formats: readonly number[] | undefined): Uint8Array {
    const list = formats ?? DEFAULT_EC_POINT_FORMATS;
    const out = new Uint8Array(1 + list.length);
    out[0] = list.length & 0xff;
    for (let i = 0; i < list.length; i++) {
        const fmt = list[i];
        /* v8 ignore next 3 */
        if (fmt === undefined) {
            throw new TlsHandshakeError("client_hello", {
                cause: new Error(`EC point format at index ${i} is missing`),
            });
        }
        out[1 + i] = fmt & 0xff;
    }
    return out;
}

function encodeApplicationSettings(alpnProtocols: readonly string[] | undefined): Uint8Array {
    const protocols = alpnProtocols !== undefined && alpnProtocols.length > 0 ? alpnProtocols : ["h2"];
    return encodeAlpn(protocols);
}

/** Default compress_certificate algorithms: brotli (0x02) only. */
const DEFAULT_COMPRESS_ALGORITHMS: readonly number[] = [0x02];

/**
 * Encode the `compress_certificate` extension body (RFC 8879) from config.
 *
 * Defaults to `[0x02]` (brotli) when the profile omits the field. Real Chrome
 * lists `[0x02, 0x01, 0x03]` (brotli, zlib, zstd) — the exact ordering and set
 * are fingerprint signals, so they flow from the profile.
 */
function encodeCompressCertificate(algorithms: readonly number[] | undefined): Uint8Array {
    const list = algorithms ?? DEFAULT_COMPRESS_ALGORITHMS;
    const out = new Uint8Array(1 + list.length * 2);
    out[0] = (list.length * 2) & 0xff;
    for (let i = 0; i < list.length; i++) {
        const algo = list[i];
        /* v8 ignore next 3 */
        if (algo === undefined) {
            throw new TlsHandshakeError("client_hello", {
                cause: new Error(`compress certificate algorithm at index ${i} is missing`),
            });
        }
        out[1 + i * 2] = (algo >> 8) & 0xff;
        out[1 + i * 2 + 1] = algo & 0xff;
    }
    return out;
}

function encodePskKeyExchangeModes(): Uint8Array {
    return new Uint8Array([0x01, 0x01]);
}

function encodeStatusRequest(): Uint8Array {
    return new Uint8Array([0x01, 0x00, 0x00, 0x00, 0x00]);
}

function encodeRenegotiationInfo(): Uint8Array {
    return new Uint8Array([0x00]);
}

/**
 * Encode a cookie extension body (RFC 8446 §4.2.2).
 *
 * Layout: `cookie_length(2) || cookie`. The cookie is an opaque blob the server
 * sent in HelloRetryRequest; the client echoes it verbatim.
 */
function encodeCookie(cookie: Uint8Array): Uint8Array {
    const out = new Uint8Array(2 + cookie.length);
    out[0] = (cookie.length >> 8) & 0xff;
    out[1] = cookie.length & 0xff;
    out.set(cookie, 2);
    return out;
}

function wrapExtension(type: number, data: Uint8Array): Uint8Array {
    const out = new Uint8Array(2 + 2 + data.length);
    out[0] = (type >> 8) & 0xff;
    out[1] = type & 0xff;
    out[2] = (data.length >> 8) & 0xff;
    out[3] = data.length & 0xff;
    out.set(data, 4);
    return out;
}

function encodeServerNameList(serverName: string): Uint8Array {
    const nameBytes = new TextEncoder().encode(serverName);
    if (nameBytes.length > 0xffff) {
        throw new TlsHandshakeError("client_hello", {
            cause: new Error("SNI server_name exceeds 65535 bytes"),
        });
    }
    const entry = new Uint8Array(1 + 2 + nameBytes.length);
    entry[0] = 0;
    entry[1] = (nameBytes.length >> 8) & 0xff;
    entry[2] = nameBytes.length & 0xff;
    entry.set(nameBytes, 3);
    const out = new Uint8Array(2 + entry.length);
    out[0] = (entry.length >> 8) & 0xff;
    out[1] = entry.length & 0xff;
    out.set(entry, 2);
    return out;
}

function encodeSupportedVersionsClient(versions: readonly ProtocolVersion[]): Uint8Array {
    const out = new Uint8Array(1 + versions.length * 2);
    out[0] = (versions.length * 2) & 0xff;
    for (let i = 0; i < versions.length; i++) {
        const version = versions[i];
        if (version === undefined) {
            throw new TlsHandshakeError("client_hello", {
                cause: new Error(`supported version at index ${i} is missing`),
            });
        }
        const wire = version.wire;
        out[1 + i * 2] = (wire >> 8) & 0xff;
        out[1 + i * 2 + 1] = wire & 0xff;
    }
    return out;
}

function encodeKeyShareClient(
    config: ClientHelloConfig,
    keyPairs: readonly KeyPair[],
    greaseValue: number,
    provider: CryptoProvider,
): Uint8Array {
    // Emit ALL offered key pairs — including post-quantum hybrid groups like
    // X25519MLKEM768 (0x11ec). They must appear in the key_share extension for
    // the JA3/JA4 fingerprint to match real browsers. The crypto backend
    // generates an X25519 key tagged with the hybrid name; the server will
    // typically select the classical X25519 group for the actual exchange.
    const greaseEntry = config.grease ? 2 + 2 + GREASE_KEY_LENGTH : 0;
    let entriesLen = greaseEntry;
    for (const kp of keyPairs) {
        entriesLen += 2 + 2 + kp.publicKey.length;
    }
    const out = new Uint8Array(2 + entriesLen);
    out[0] = (entriesLen >> 8) & 0xff;
    out[1] = entriesLen & 0xff;
    let o = 2;
    if (config.grease) {
        out[o++] = (greaseValue >> 8) & 0xff;
        out[o++] = greaseValue & 0xff;
        out[o++] = (GREASE_KEY_LENGTH >> 8) & 0xff;
        out[o++] = GREASE_KEY_LENGTH & 0xff;
        out.set(provider.randomBytes(GREASE_KEY_LENGTH), o);
        o += GREASE_KEY_LENGTH;
    }
    for (const kp of keyPairs) {
        const groupWire = namedGroupToWire(kp.algorithm);
        out[o++] = (groupWire >> 8) & 0xff;
        out[o++] = groupWire & 0xff;
        out[o++] = (kp.publicKey.length >> 8) & 0xff;
        out[o++] = kp.publicKey.length & 0xff;
        out.set(kp.publicKey, o);
        o += kp.publicKey.length;
    }
    return out;
}

function encodeSignatureAlgorithms(algorithms: readonly SignatureScheme[]): Uint8Array {
    const out = new Uint8Array(2 + algorithms.length * 2);
    out[0] = ((algorithms.length * 2) >> 8) & 0xff;
    out[1] = (algorithms.length * 2) & 0xff;
    for (let i = 0; i < algorithms.length; i++) {
        const scheme = algorithms[i];
        if (scheme === undefined) {
            throw new TlsHandshakeError("client_hello", {
                cause: new Error(`signature algorithm at index ${i} is missing`),
            });
        }
        const wire = signatureSchemeToWire(scheme);
        out[2 + i * 2] = (wire >> 8) & 0xff;
        out[2 + i * 2 + 1] = wire & 0xff;
    }
    return out;
}

function encodeAlpn(protocols: readonly string[]): Uint8Array {
    let entriesLen = 0;
    for (const proto of protocols) {
        const encoded = new TextEncoder().encode(proto);
        if (encoded.length === 0 || encoded.length > 0xff) {
            throw new TlsHandshakeError("client_hello", {
                cause: new Error(`ALPN protocol must be 1..255 bytes: "${proto}"`),
            });
        }
        entriesLen += 1 + encoded.length;
    }
    const out = new Uint8Array(2 + entriesLen);
    out[0] = (entriesLen >> 8) & 0xff;
    out[1] = entriesLen & 0xff;
    let o = 2;
    for (const proto of protocols) {
        const encoded = new TextEncoder().encode(proto);
        out[o++] = encoded.length & 0xff;
        out.set(encoded, o);
        o += encoded.length;
    }
    return out;
}
