/**
 * Regression tests for the three critical ClientHello bugs, verified against the
 * real chrome-140 profile fingerprint (cipher suites, extension order, GREASE).
 *
 * These tests encode the invariants the fix establishes:
 *   1. cipherSuiteToWire() maps EVERY offered cipher suite — including TLS 1.2
 *      suites and the GREASE placeholder — to a valid non-zero 2-byte IANA wire
 *      value. Before the fix, the unknown suites fell through to a default that
 *      returned undefined, silently emitting 0x0000 and getting `decode_error`.
 *   2. buildClientHelloExtensions() emits extensions in the EXACT order the
 *      profile specifies, and emits ALL of them (chrome-140 has 16). Before the
 *      fix it hardcoded 5 extensions and ignored the profile order.
 *   3. GREASE values are generated when grease=true: a GREASE cipher suite at the
 *      front, a GREASE extension, and a GREASE key-share group.
 *
 * Each test is constructed so it would FAIL on the pre-fix code and PASS after.
 */

import { describe, it, expect } from "vitest";
import { crypto } from "@browsercore/crypto";
import { buildClientHello } from "../src/handshake/client-hello.js";
import { cipherSuiteToWire } from "../src/handshake/client-hello.js";
import { ExtensionType } from "../src/extensions/extensions.js";
import { TLS_1_3 } from "../src/types.js";
import type { ClientHelloConfig, KeyPair } from "../src/types.js";

/** The chrome-140 profile's offered cipher suite list (in preference order). */
const CHROME140_CIPHER_SUITES = [
    "TLS_GREASE_RESERVED_0",
    "TLS_AES_128_GCM_SHA256",
    "TLS_AES_256_GCM_SHA384",
    "TLS_CHACHA20_POLY1305_SHA256",
    "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
    "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
    "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
    "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
    "TLS_RSA_WITH_AES_128_GCM_SHA256",
    "TLS_RSA_WITH_AES_256_GCM_SHA384",
    "TLS_RSA_WITH_AES_128_CBC_SHA",
    "TLS_RSA_WITH_AES_256_CBC_SHA",
] as const;

/** The chrome-140 profile's exact extension order (GREASE prepended at runtime). */
const CHROME140_EXTENSION_ORDER = [
    0, 10, 11, 13, 16, 17513, 18, 23, 27, 35, 41, 43, 45, 5, 51, 65281,
];

function chrome140Config(): ClientHelloConfig {
    return {
        cipherSuites: [...CHROME140_CIPHER_SUITES],
        extensionOrder: [...CHROME140_EXTENSION_ORDER],
        keyShareGroups: ["x25519", "secp256r1"],
        signatureAlgorithms: [
            "ecdsa_secp256r1_sha256",
            "rsa_pss_rsae_sha256",
            "rsa_pkcs1_sha256",
            "ecdsa_secp384r1_sha384",
            "rsa_pss_rsae_sha384",
            "rsa_pkcs1_sha384",
        ],
        supportedVersions: [TLS_1_3],
        serverName: "example.com",
        alpnProtocols: ["h2", "http/1.1"],
        grease: true,
    };
}

async function makeKeyPairs(): Promise<readonly KeyPair[]> {
    const kp = crypto.x25519GenerateKeyPair();
    return [
        { algorithm: "x25519", privateKey: kp.secretKey, publicKey: kp.publicKey },
        // secp256r1 isn't generated by the crypto backend, but the handshake driver
        // filters to supported groups, so a single x25519 share suffices here.
    ];
}

/** Walk a serialized ClientHello to its length-prefixed extensions block. */
function extractExtensionsBlock(hello: Uint8Array): Uint8Array {
    let o = 4; // handshake header: type(1) + length(3)
    o += 2 + 32; // legacy_version(2) + random(32)
    const sidLen = hello[o]!;
    o += 1 + sidLen;
    const csLen = (hello[o]! << 8) | hello[o + 1]!;
    o += 2 + csLen;
    const compLen = hello[o]!;
    o += 1 + compLen;
    const extStart = o;
    const extLen = (hello[o]! << 8) | hello[o + 1]!;
    return hello.subarray(extStart, extStart + 2 + extLen);
}

/** Parse the extensions block into { type, data } records (with 2-byte prefix). */
function parseExtensions(buf: Uint8Array): ReadonlyArray<{ type: number; data: Uint8Array }> {
    let o = 0;
    const total = (buf[o++]! << 8) | buf[o++]!;
    const end = o + total;
    const out: { type: number; data: Uint8Array }[] = [];
    while (o < end) {
        const type = (buf[o++]! << 8) | buf[o++]!;
        const dataLen = (buf[o++]! << 8) | buf[o++]!;
        out.push({ type, data: buf.subarray(o, o + dataLen) });
        o += dataLen;
    }
    return out;
}

describe("Bug 1: cipherSuiteToWire maps every offered suite to a valid wire value", () => {
    it("maps every chrome-140 cipher suite to a non-zero 2-byte IANA value", () => {
        // Pre-fix: the 5th suite (TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256) and all
        // subsequent ones hit the default and returned undefined → 0x0000 on the wire.
        for (const suite of CHROME140_CIPHER_SUITES) {
            const wire = cipherSuiteToWire(suite);
            expect(wire).toBeGreaterThan(0);
            expect(wire).toBeLessThanOrEqual(0xffff);
        }
    });

    it("maps the GREASE placeholder to the canonical 0x0a0a sentinel", () => {
        expect(cipherSuiteToWire("TLS_GREASE_RESERVED_0")).toBe(0x0a0a);
    });

    it("maps the TLS 1.2 suites to their correct IANA codes (not 0x0000)", () => {
        // Spot-check the TLS 1.2 suites that pre-fix silently became 0x0000.
        expect(cipherSuiteToWire("TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256")).toBe(0xc02b);
        expect(cipherSuiteToWire("TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256")).toBe(0xc02f);
        expect(cipherSuiteToWire("TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA")).toBe(0xc013);
        expect(cipherSuiteToWire("TLS_RSA_WITH_AES_128_CBC_SHA")).toBe(0x002f);
        expect(cipherSuiteToWire("TLS_RSA_WITH_AES_256_CBC_SHA")).toBe(0x0035);
    });

    it("never emits 0x0000 for any chrome-140 offered suite", async () => {
        const config = chrome140Config();
        const kps = await makeKeyPairs();
        const hello = buildClientHello(config, kps);
        // Walk to cipher_suites and assert no 0x0000 pair.
        let o = 4 + 2 + 32;
        o += 1 + hello[o]!; // session id
        const csLen = (hello[o]! << 8) | hello[o + 1]!;
        o += 2;
        for (let i = 0; i < csLen; i += 2) {
            const wire = (hello[o + i]! << 8) | hello[o + i + 1]!;
            expect(wire).not.toBe(0x0000);
        }
    });
});

describe("Bug 2: extensions are emitted in the profile's exact order, all 16 of them", () => {
    it("emits extensions in the exact order chrome-140 specifies (GREASE first)", async () => {
        // Pre-fix: only 5 hardcoded extensions were emitted, in a fixed order that
        // ignored the profile entirely.
        const config = chrome140Config();
        const kps = await makeKeyPairs();
        const hello = buildClientHello(config, kps);
        const extBlock = extractExtensionsBlock(hello);
        const extensions = parseExtensions(extBlock);
        const types = extensions.map((e) => e.type);

        // GREASE (0x0a0a) prepended, then the profile's 16 in order.
        const expected = [0x0a0a, ...CHROME140_EXTENSION_ORDER];
        expect(types).toEqual(expected);
    });

    it("emits all 16 profile extensions (not just the 5 hardcoded ones)", async () => {
        const config = chrome140Config();
        const kps = await makeKeyPairs();
        const hello = buildClientHello(config, kps);
        const extBlock = extractExtensionsBlock(hello);
        const extensions = parseExtensions(extBlock);
        // 1 GREASE + 16 profile extensions.
        expect(extensions).toHaveLength(1 + CHROME140_EXTENSION_ORDER.length);
    });

    it("honors a profile order that omits ALPN when type 16 is absent", async () => {
        // A profile whose extensionOrder lacks ALPN must not emit ALPN, even though
        // the old code unconditionally hardcoded it.
        const config: ClientHelloConfig = {
            cipherSuites: ["TLS_AES_128_GCM_SHA256"],
            extensionOrder: [0, 43, 51], // SNI, supported_versions, key_share only
            keyShareGroups: ["x25519"],
            signatureAlgorithms: ["ecdsa_secp256r1_sha256"],
            supportedVersions: [TLS_1_3],
            serverName: "example.com",
            grease: false,
        };
        const kps = await makeKeyPairs();
        const hello = buildClientHello(config, kps);
        const extBlock = extractExtensionsBlock(hello);
        const extensions = parseExtensions(extBlock);
        const types = extensions.map((e) => e.type);
        expect(types).toEqual([0, 43, 51]);
        expect(types).not.toContain(ExtensionType.APPLICATION_LAYER_PROTOCOL_NEGOTIATION);
    });
});

describe("Bug 3: GREASE values are generated when grease=true", () => {
    it("prepends a GREASE cipher suite (0x0a0a) at the front of the list", async () => {
        const config = chrome140Config();
        const kps = await makeKeyPairs();
        const hello = buildClientHello(config, kps);
        let o = 4 + 2 + 32;
        o += 1 + hello[o]!; // session id
        const csLen = (hello[o]! << 8) | hello[o + 1]!;
        o += 2;
        expect(csLen).toBeGreaterThan(0);
        const firstWire = (hello[o]! << 8) | hello[o + 1]!;
        expect(firstWire).toBe(0x0a0a);
    });

    it("prepends a GREASE extension (type 0x0a0a) ahead of the profile order", async () => {
        const config = chrome140Config();
        const kps = await makeKeyPairs();
        const hello = buildClientHello(config, kps);
        const extBlock = extractExtensionsBlock(hello);
        const extensions = parseExtensions(extBlock);
        expect(extensions[0]!.type).toBe(0x0a0a);
    });

    it("prepends a GREASE key-share group (0x0a0a) in the key_share extension", async () => {
        const config = chrome140Config();
        const kps = await makeKeyPairs();
        const hello = buildClientHello(config, kps);
        const extBlock = extractExtensionsBlock(hello);
        const extensions = parseExtensions(extBlock);
        const ks = extensions.find((e) => e.type === ExtensionType.KEY_SHARE);
        expect(ks).toBeDefined();
        // key_share body: client_shares_len(2) || share { group(2), len(2), key }.
        const data = ks!.data;
        const firstGroup = (data[2]! << 8) | data[3]!;
        expect(firstGroup).toBe(0x0a0a);
    });

    it("emits NO GREASE values when grease=false (firefox-style profile)", async () => {
        const config: ClientHelloConfig = {
            cipherSuites: ["TLS_AES_128_GCM_SHA256"],
            extensionOrder: [0, 43, 51],
            keyShareGroups: ["x25519"],
            signatureAlgorithms: ["ecdsa_secp256r1_sha256"],
            supportedVersions: [TLS_1_3],
            serverName: "example.com",
            grease: false,
        };
        const kps = await makeKeyPairs();
        const hello = buildClientHello(config, kps);

        // No GREASE cipher suite at the front.
        let o = 4 + 2 + 32;
        o += 1 + hello[o]!;
        const firstCipherWire = (hello[o + 2]! << 8) | hello[o + 3]!;
        expect(firstCipherWire).not.toBe(0x0a0a);

        // No GREASE extension or key-share group.
        const extBlock = extractExtensionsBlock(hello);
        const extensions = parseExtensions(extBlock);
        const types = extensions.map((e) => e.type);
        expect(types[0]).not.toBe(0x0a0a);
        const ks = extensions.find((e) => e.type === ExtensionType.KEY_SHARE);
        const firstGroup = (ks!.data[2]! << 8) | ks!.data[3]!;
        expect(firstGroup).not.toBe(0x0a0a);
    });
});
